# from doctrine/instantiator:
# https://github.com/doctrine/instantiator/blob/97aa11bb71ad6259a8c5a1161b4de2d6cdcc5501/.github/workflows/continuous-integration.yml

name: "CI"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"
    continue-on-error: ${{ matrix.can-fail }}

    strategy:
      matrix:
        include:
          - php-version: 7.2
            composer-flags: "--prefer-lowest --prefer-stable"
            can-fail: false
          - php-version: 7.3
            composer-flags: "--prefer-stable"
            can-fail: false
          - php-version: 7.4
            composer-flags: "--prefer-stable"
            symfony-require: "4.4.*"
            can-fail: false
          - php-version: 7.4
            composer-flags: "--prefer-stable"
            symfony-require: "5.3.*"
            can-fail: false
            coverage: yes
          - php-version: 7.4
            composer-flags: "--prefer-stable"
            can-fail: false
            symfony-require: "5.4.*"
          - php-version: 8.0
            composer-flags: "--prefer-stable"
            can-fail: false
            symfony-require: "6.0.*"
          - php-version: 8.1
            composer-flags: "--prefer-stable"
            can-fail: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.coverage != '' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "xdebug"
          tools: "composer:v2,flex"

      - name: "Install PHP without coverage"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.coverage == '' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          tools: "composer:v2,flex"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: |
          composer remove friendsofphp/php-cs-fixer --dev --no-update
          composer update --no-interaction --no-progress ${{ matrix.composer-flags }}

      - name: "Run PHPUnit"
        if: "${{ matrix.coverage != '' }}"
        run: |
          XDEBUG_MODE=coverage ./phpunit --coverage-clover=coverage.clover
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover

      - name: "Run PHPUnit"
        if: "${{ matrix.coverage == '' }}"
        run: "./phpunit"
